apiVersion: v1
kind: Service
metadata:
  labels:
    app: arcade-balance-db
  name: arcade-balance-db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: arcade-balance-db
