version: '3.4'

volumes:
  live-certs:

networks:
  pmm:
    external: true
  elk:
    external: true

services:
  app:
    networks:
      - default
    environment:
      - RAILS_ENV=staging
      - ENABLE_ROLLBAR=true
      - LOG_LEVEL=info
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=weallalive137
      - POSTGRES_DB=arcade-balance-db
      - ORIGIN_URL=//admin.arcade.staging.server-planet-gold-rush.com:8080
      - VIRTUAL_HOST=http://admin.arcade.staging.server-planet-gold-rush.com:8080/*,https://admin.arcade.staging.server-planet-gold-rush.com:8080/*
      - DOCKERCLOUD_CONTAINER_HOSTNAME=app-{{.Task.Slot}}
    image: 'planetgr/arcade-balance:r0.0.1'
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.app == true
          - node.labels.cluster-name == arcade

  arcade-balance-db:
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=weallalive137
      - POSTGRES_USER=root
    image: 'postgres'
    ports:
      - '5432'
    restart: always
    volumes:
      - /var/lib/data/arcade-balance-db/postgresql:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.db == true
          - node.labels.cluster-name == arcade

  letsencrypt:
    networks:
      - default
    environment:
      - DOMAINS=admin.arcade.staging.server-planet-gold-rush.com
      - EMAIL=admin@one1eleven.com
      - EXCLUDE_BASIC_AUTH=true
      - LOAD_BALANCER_SERVICE_NAME=web-balancer
      - SERVICE_PORTS=8080
      - VIRTUAL_HOST=http://*/.well-known/acme-challenge/*
      - VIRTUAL_HOST_WEIGHT=100000
    image: 'yard/letsencrypt:latest'
    volumes:
      - live-certs:/etc/letsencrypt
    deploy:
      placement:
        constraints:
          - node.labels.balancer == true
          - node.labels.cluster-name == arcade