apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: arcade-balance-db-claim
  name: arcade-balance-db-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
