apiVersion: v1
kind: Service
metadata:
  labels:
    app: arcade-balance-db-ext
  name: arcade-balance-db-ext
spec:
  type: NodePort
  ports:
  - name: "5432-ext"
    port: 5432
    nodePort: 31002
  selector:
    app: arcade-balance-db
