apiVersion: batch/v1
kind: Job
metadata:
  name: arcade-balance-migration
spec:
  template:
    spec:
      containers:
      - name: arcade-balance-migration
        image: planetgr/arcade-balance:v.master-923ef56
        env:
        - name: RAILS_ENV
          value: production
        - name: ENABLE_ROLLBAR
          value: "false"
        - name: LOG_LEVEL
          value: info
        - name: POSTGRES_DB
          value: arcade-balance-db
        - name: POSTGRES_PASSWORD
          value: weallalive137
        - name: POSTGRES_USER
          value: app_arcade
        - name: ARCADE_DB_USER
          value: app_arcade
        - name: ARCADE_DB_URL
          value: arcade-db
        - name: ARCADE_DB_NAME
          value: arcade_prod
        - name: ORIGIN_URL
          value: //admin.arcade.staging.server-planet-gold-rush.com:8080
        - name: VIRTUAL_HOST
          value: http://admin.arcade.staging.server-planet-gold-rush.com:8080/*
        - name: DOCKERCLOUD_CONTAINER_HOSTNAME
          value: balance-1
        - name: CHALLENGE_SERVER_URL
          value: http://challenge
        - name: ARCADE_SERVER_URL
          value: http://arcade
        - name: INTERNAL_TOKEN
          value: zHjjMM1OH5-zpDDQESDwlWRE90YSh-kJzm9-yNj-oQyffUVvQfhQzzAECU1g2urZ3mc
      restartPolicy: Never
