# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  reconnect: true

development:
  <<: *default
  host: localhost
  database: arcade-balance-db

staging:
  <<: *default
  host: arcade-balance-db
  database: <%= ENV["POSTGRES_DB"] %>

arcade:
  <<: *default
  host: <%= ENV["ARCADE_DB_URL"] %>
  database: <%= ENV["ARCADE_DB_NAME"] %>

test:
  <<: *default
  host: localhost
  database: <%= ENV["POSTGRES_DB"] %>

production:
  <<: *default
  host: arcade-balance-db
  database: <%= ENV["POSTGRES_DB"] %>

